name: Update README Timestamp

on:
  push:
    branches:
      - main  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README date and time (Jakarta time WIB)
        run: |
          # Set TZ to Asia/Jakarta
          export TZ="Asia/Jakarta"
          timestamp=$(date +"%d-%m-%Y %H:%M:%S %Z")
          # replace line starting with "Last Updated:"
          sed -i "s/^Last Updated:.*/Last Updated: $timestamp/" README.md
          echo "Updated README timestamp to $timestamp"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README timestamp" || echo "No changes to commit"
          git push
